### ISSUE TITLE
Cannot subscribe to a list group

### ISSUE THREAD

**Issue by saimiris** [spatie/laravel-newsletter#88] opened 2017-06-22 10:43 UTC
Hi there,

I successfully subscribed to a MailChimp list thanks to your excellent API, but I cannot subscribe to a given list group.

My code follows your guidelines: Newsletter::subscribe($request->input('email'), null, 'test', ['groups' => ['45' => true]]), 'test' being the name of my list and '45' being the ID of my group. But it does not work. The user gets successfully subscribed to the list but he is not part of any group.

Best regards,

**Comment by freekmurze** [comment] 2017-06-22 20:10
Are you sure `['groups' => ['45' => true]]`. We just pass these options to the MailChimp API:
https://github.com/spatie/laravel-newsletter/blob/master/src/Newsletter.php#L65-L67

**Comment by saimiris** [comment] 2017-06-23 08:07
Hi @freekmurze thanks a lot for your fast answer.

Yes I am absolutely sure. Look, this would be the URL to see the members of the group: https://us11.admin.mailchimp.com/lists/members/?id=220573&group_id=45
so the group ID is 45.

And I am 100% of the list ID I use, since the user is correctly subscribed to the list but, as I said, not tagged in any group.

**Comment by freekmurze** [comment] 2017-06-23 10:54
I'd accept a PR that fixes this.

**Comment by saimiris** [comment] 2017-06-26 08:19
@freekmurze Some new?

**Comment by freekmurze** [comment] 2017-06-26 08:37
Nope, and I am not going to have time to recreate your problem. If you want a quick solution, it's best to dive in yourself and investigate it. If it turns out that the problem is caused by this package, I'd accept a fully tested PR that fixes it.

**Comment by saimiris** [comment] 2017-06-26 10:56
The is no bug. My group_id was wrong. It is actually quite complicated to get it. This thread shows it how to get it: https://stackoverflow.com/questions/32559234/add-to-interest-group-using-mailchimp-api-v3

The syntax ['interests'=>['interestId'=>true, 'interestId'=>true] is right. It should always be 'interests' and not 'groups'.

**Comment by freekmurze** [comment] 2017-06-26 12:06
Glad you found it, I assume it's ok to close this issue now.

**Closed by freekmurze** 2017-06-26 12:06 UTC
Labels: bug, help wanted
