### ISSUE TITLE
updateEmailAddress() only works for default list

### ISSUE THREAD

**Issue by jjmu15** [spatie/laravel-newsletter#199] opened 2019-04-17 14:21 UTC
When trying to update the email address on lists other than the default, this won't work.

Tried specifying the list name as final parameter as per other examples with no luck.

**Comment by freekmurze** [comment] 2019-04-24 13:57
I don't have time to look into this now, but feel free to submit a PR with tests that fixes this.

**Comment by monaye** [comment] 2019-04-24 15:26
@jjmu15 Could you upload a screenshot or captured video of the bug?

**Comment by elmudometal** [comment] 2019-05-02 21:45
something like this happened to me, the problem that I noticed is that the lists are a static collection therefore it is not updated automatically, what I did was overwrite the lib so that all this part was more dynamic with functions like
* getList
* getLists
* updateList
* createList
* sendCampaign
* testCampaign

eliminating the dependence on the list collection that prevents intalar in laravel <5.8

**Comment by atymic** [comment] 2019-06-01 02:22
I'll have a look into this when I have a chance :)

**Comment by samcoppock** [comment] 2019-10-19 15:49
i have looked into this and was not able to reproduce the problem

steps takes to reproduce 
(note i only have one list due to having a free mailchimp account so both my 'subscribers' and 'secondary' list point to the same mailchimp audience

1)
setup the following lists in newsletter.php

    /*
     * The listName to use when no listName has been specified in a method.
     */
    'defaultListName' => 'subscribers',

    /*
     * Here you can define properties of the lists.
     */

    'lists' => [

        /*
         * This key is used to identify this list. It can be used
         * as the listName parameter provided in the various methods.
         *
         * You can set it to any string you want and you can add
         * as many lists as you want.
         */
        'subscribers' => [

            /*
             * A MailChimp list id. Check the MailChimp docs if you don't know
             * how to get this value:
             * http://kb.mailchimp.com/lists/managing-subscribers/find-your-list-id.
             */
            'id' => env('MAILCHIMP_LIST_ID'),
        ],
		'secondary' => [
			'id' => env('MAILCHIMP_LIST_ID'),
		]
    ],

2)
Run the following set of commands and manual tests

		Newsletter::subscribe('me@mail.com');
- manually check that 'me@mail.com' appears in the mailchimp audience
		Newsletter::updateEmailAddress('me@mail.com', 'the.luggage@discworld.com');
- manually check that the only address in the mailchimp audience is 'the.luggage@discworld.com'
      Newsletter::updateEmailAddress('the.luggage@discworld.com','someone@mail.com','secondary');
- manually check that the only address in the mailchimp audience is 'someone@mail.com'

**Comment by freekmurze** [comment] 2019-10-20 19:46
Closing because problem cannot be reproduced.

**Closed by freekmurze** 2019-10-20 19:46 UTC
Labels: bug, good first issue, help wanted
